dotfiles_path = "~/dotfiles"
log = false

[variable.name]
var = "gingama4"
[variable.email]
var = "gingama4@gmail.com"

[[dotfile]]
name = "vim"  

  [[dotfile.step]]
  name = "make .vim"
  target = "~/.vim"
  type = "mkdir"

  [[dotfile.step]]
  name = "link vimrc"
  src = "vim/vimrc"
  target = "~/.vimrc"
  type = "ln"
  force = true

  [[dotfile.step]]
  name = "link plugin.vim"
  src = "vim/plugin.vim"
  target = "~/.vim/plugin.vim"
  type = "ln"
  force = true

  [[dotfile.step]]
  name = "link rc"
  src = "vim/rc"
  target = "~/.vim/rc"
  type = "ln"
  force = true

[[dotfile]]
name = "git"  

  [[dotfile.step]]
  name = "copy .gitconfig"
  src = ".gitconfig"
  target = "~/.gitconfig"
  type = "cp"

  [[dotfile.step]]
  name = "git config name"
  type = "cmd"
  cmd = "git config --global user.name {{.name}}"

  [[dotfile.step]]
  name = "git config email"
  type = "cmd"
  cmd = "git config --global user.email {{.email}}"

[[dotfile]]
name = "test"
  
  [[dotfile.step]]
  name = "test mkdir"
  target = "~/dotter-test"
  type = "mkdir"
