version: '3'
services:
  ubuntu:
    build: ./docker/ubuntu/
    volumes:
      - .:/home/dottest/dotfiles
    environment:
      - INSTALL_DIR=/home/dottest/dotfiles
      - CI=1
      - XDG_RUNTIME_DIR=/run/user/1000
    command: ./dotfiles/install.sh install
  arch:
    build: ./docker/arch/
    volumes:
      - .:/home/dottest/dotfiles
    environment:
      - INSTALL_DIR=/home/dottest/dotfiles
      - CI=1
      - XDG_RUNTIME_DIR=/run/user/1000
    command: ./dotfiles/install.sh install

