[[plugins]]
repo = 'Shougo/dein.vim'

# Language Server Protocol
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = 0

[[plugins]]
repo = 'mattn/vim-lsp-icons'

# resize window size
[[plugins]]
repo = 'simeji/winresizer'

# color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'

# status bar
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {
		\ 'colorscheme': 'iceberg',
		\ 'active': {
			\ 'left': [ ['mode', 'paste'], ['readonly', 'branchName', 'filepath', 'modified'] ]
			\ },
		\ 'component_function':{
			\ 'filepath': 'FilePath',
			\ },
		\ }

	function! FilePath()
		if winwidth(0) > 90
			return expand("%:s")
		else
			return expand("%:t")
		endif
	endfunction

	" # show statusbar
	set laststatus=2
	" # hide --INSERT--
	" set noshowmode
'''

# folder tree
[[plugins]]
repo = 'scrooloose/nerdtree'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'

# NERD Font
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# EditorConfig
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

