name: Test

on: [push]

jobs:
  arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Update packages
        run: pacman -Syyu --noconfirm
      - name: Install required packages
        run: pacman -S --noconfirm git sudo wget
      - name: Install dotfiles
        run: |
          set -e
          export CI=1
          export XDG_RUNTIME_DIR="/run/user/1000"
          bash ./install.sh -d "$GITHUB_WORKSPACE"
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install required packaged
        run: apt update && apt install -y git sudo wget
      - name: Install dotfiles
        run: |
          set -e
          export CI=1
          export XDG_RUNTIME_DIR="/run/user/1000"
          bash ./install.sh -d "$GITHUB_WORKSPACE"
